name = "vid-just"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

# R2 Bucket binding - your actual bucket name
[[r2_buckets]]
binding = "VIDEO_BUCKET"
bucket_name = "just-vids"
preview_bucket_name = "just-vids-preview"

# Environment variables - replace with your actual Cloudflare Account ID
[vars]
ACCOUNT_ID = "your-cloudflare-account-id"

# Optional: Custom domain
# routes = [
#   { pattern = "videos.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
