name = "video-anywhere-box"
main = "worker.js"
compatibility_date = "2024-01-01"

# Environment variables for Cloudflare Stream
[vars]
STREAM_API_TOKEN = "nz3V5siUHVPhnjJxYm_cHdWiV-kNCRC-9gYsl1DQ"
STREAM_ACCOUNT_ID = "b5f7bbc74ed9bf4c44b19d1f3b937e22"
STREAM_CUSTOMER_CODE = "aanhjdlw75bwi5za"

# Optional: Custom domain
# routes = [
#   { pattern = "videos.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
